---
- name: install go
  homebrew:
    name: go
    state: latest

- name: create gopath directory
  file:
    path: "~/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - src
    - pkg
    - bin

- name: touch golang.zsh
  file:
    path: ~/bin/zsh/golang.zsh
    state: touch

- name: create golang.zsh
  copy:
    content: |
        export GOPATH=$HOME
        export GOBIN=$GOPATH/bin
        export GOROOT=/usr/local/opt/go/libexec
        export PATH=$PATH:$GOBIN:$GOROOT/bin
    dest: ~/bin/zsh/golang.zsh
