---
- name: install go
  homebrew:
    name: go
    state: latest

- name: create gopath directory
  file:
    path: "~/src/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - go
    - go/src
    - go/pkg
    - go/bin

- name: touch golang.zsh
  file:
    path: ~/bin/zsh/golang.zsh
    state: touch

- name: create golang.zsh
  copy:
    content: |
        export GOPATH=~/src/go
        export GOROOT=/usr/local/opt/go/libexec
        export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
    dest: ~/bin/zsh/golang.zsh
