---
- name: install go
  homebrew:
    name: go
    state: latest

- name: create gopath directory
  file:
    path: ~/.gopath
    state: directory
    mode: 0755

- name: touch golang.zsh
  file:
    path: ~/bin/zsh/golang.zsh
    state: touch

- name: create golang.zsh
  copy:
    content: |
        export GOPATH=~/.gopath
        export PATH=$PATH:$GOPATH/bin
    dest: ~/bin/zsh/golang.zsh
