---
- name: add to sudoers without password
  become: yes
  lineinfile: >
    dest=/etc/sudoers
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=true
  with_items:
    - { regexp: '^#\s*%wheel\s+ALL=(ALL)\s+NOPASSWD:\s+ALL', line: '%wheel\tALL=(ALL) NOPASSWD: ALL' }
