---
- name: add to sudoers without password
  become: yes
  lineinfile: >
    dest=/etc/sudoers
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    backrefs=yes
    create=true
  with_items:
    - { regexp: '%admin\s+ALL=\(ALL\)\s+ALL', line: '%admin\tALL=(ALL) NOPASSWD: ALL' }
