---
- hosts: 127.0.0.1
  connection: local

  roles:
    - role: osx_defaults
    - role: computername
      when: computername is defined
    - role: ssh_config
    - role: sudoers
    - role: terminal
    - role: git
    #- role: dotfiles
    - role: homebrew
    # below roles depend on homebrew
    #- role: zsh
    - role: vim

  vars:
    - username: "{{ lookup('env', 'USER') }}"

    - brew_apps:
      - htop-osx
      - jq
      - markdown
      - pandoc
      - the_silver_searcher
      - irssi

    - brew_cask_apps:
      - alfred
      - slate
      - rescuetime
      - flux
      - 1password
      - typinator
      - slack
      - google-chrome
      - evernote
      - omnifocus
      - dropbox
      - spotify
      - sonos
      - kaleidoscope
      - vagrant
      - virtualbox
