---
- hosts: 127.0.0.1
  connection: local

  roles:
    - role: osx_defaults
    - role: computername
      when: computername is defined
    - role: sudoers
    - role: terminal
    - role: ssh_config
    - role: git
    - role: vim
    - role: zsh

  vars:
    - username: "{{ lookup('env', 'USER') }}"

    - brew_apps:
      - tmux
      - the_silver_searcher
      - jq
      - htop-osx
      - irssi
      - markdown
      - pandoc

    - brew_cask_apps:
      - 1password
      - alfred
      - dropbox
      - evernote
      - flux
      - google-chrome
      - kaleidoscope
      - kindle
      - omnifocus
      - rescuetime
      - slack
      - slate
      - sonos
      - spotify
      - typinator
      - vagrant
      - virtualbox
