---
- hosts: 127.0.0.1
  connection: local

  roles:
    - role: osx_defaults
      tags: osx
    - role: computername
      when: computername is defined
      tags: computername
    - role: ssh_config
      tags: ssh
    - role: sudoers
      tags: sudoers
    - role: terminal
      tags: terminal
    - role: git
      tags: git
    - role: homebrew
      tags: homebrew
    # below roles depend on homebrew
    - role: vim
      tags: vim
    - role: zsh
      tags: zsh

  vars:
    - username: "{{ lookup('env', 'USER') }}"

    - brew_apps:
      - tmux
      - the_silver_searcher
      - jq
      - htop-osx
      - irssi
      - markdown
      - pandoc

    - brew_cask_apps:
      - alfred
      - slate
      - rescuetime
      - flux
      - 1password
      - typinator
      - slack
      - google-chrome
      - evernote
      - omnifocus
      - dropbox
      - spotify
      - sonos
      - kaleidoscope
      - vagrant
      - virtualbox
