#!/bin/bash

PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin

SITE_YAML=/usr/local/nest/config/site.yaml

while [[ $# > 1 ]]; do
    opt="$1"
    case $opt in
        -r|--role)
            role="$2"
            shift
            ;;
        -b|--branch)
            branch="$2"
            shift
            ;;
        -n|--computer-name)
            computername="-e computername='$2'"
            shift
            ;;
        -e|--extra)
            extra_ansible_opts="$2"
            shift
            ;;
        *)
            ;;
    esac
    shift
done

green='\e[1;32m'  # green
red='\e[1;31m'    # red
off='\e[0m'       # reset

function setStatusMessage {
    printf "${IRed} --> ${green}$1${off}\n" 1>&2
}

function triggerError {
    printf "${red} --> $1 ${off}\n" 1>&2
    exit 1
}

function exists {
    if command -v $1 >/dev/null 2>&1
    then
        return 0
    else
        return 1
    fi
}

# https://github.com/boxcutter/osx/blob/master/script/xcode-cli-tools.sh
function install_clt {
    # Get and install Xcode CLI tools
    OSX_VERS=$(sw_vers -productVersion | awk -F "." '{print $2}')

    # on 10.9+, we can leverage SUS to get the latest CLI tools
    if [ "$OSX_VERS" -ge 9 ]; then
        # create the placeholder file that's checked by CLI updates' .dist code
        # in Apple's SUS catalog
        touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
        # find the CLI Tools update
        PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
        # install it
        softwareupdate -i "$PROD" -v
        rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

    # on 10.7/10.8, we instead download from public download URLs, which can be found in
    # the dvtdownloadableindex:
    # https://devimages.apple.com.edgekey.net/downloads/xcode/simulators/index-3905972D-B609-49CE-8D06-51ADC78E07BC.dvtdownloadableindex
    else
        [ "$OSX_VERS" -eq 7 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_xcode_os_x_lion_april_2013.dmg
        [ "$OSX_VERS" -eq 7 ] && ALLOW_UNTRUSTED=-allowUntrusted
        [ "$OSX_VERS" -eq 8 ] && DMGURL=http://devimages.apple.com.edgekey.net/downloads/xcode/command_line_tools_for_osx_mountain_lion_april_2014.dmg

        TOOLS=clitools.dmg
        curl "$DMGURL" -o "$TOOLS"
        TMPMOUNT=`mktemp -d /tmp/clitools.XXXX`
        hdiutil attach "$TOOLS" -mountpoint "$TMPMOUNT"
        installer $ALLOW_UNTRUSTED -pkg "$(find $TMPMOUNT -name '*.mpkg')" -target /
        hdiutil detach "$TMPMOUNT"
        rm -rf "$TMPMOUNT"
        rm "$TOOLS"
        exit
    fi
}

setStatusMessage "Checking if we need to ask for a sudo password"
sudo -v

setStatusMessage "Keep-alive: update existing sudo time stamp until we are finished"

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

if [[ ! -f "/Library/Developer/CommandLineTools/usr/bin/clang" ]]; then
    setStatusMessage "Install the CLT"
    install_clt
fi

if ! exists pip; then
    setStatusMessage "Install PIP"
    sudo easy_install --quiet pip
fi
if ! exists ansible; then
    setStatusMessage "Install Ansible"
    sudo pip install -q ansible
fi

setStatusMessage "Create necessary folders"
sudo mkdir -p /usr/local/nest
sudo mkdir -p /usr/local/nest/roles
sudo chmod -R g+rwx /usr/local
sudo chgrp -R admin /usr/local

if [ ! -f $SITE_YAML ]; then
    # Create base site.yaml
    cat >$SITE_YAML <<EOL
#
# Generated on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
---
- hosts: 127.0.0.1
  connection: local

  roles:
    - role: base
EOL
fi
setStatusMessage "Configured base playbook"

if [ ! -z "$role" ]; then
    # Add specified roles to site.yaml
    for r in $(echo $role | sed "s/,/ /g"); do
        cat >>$SITE_YAML <<EOL
    - role: $r
EOL
    done
    setStatusMessage "Configured additional role(s): $role"
fi

if [ -z "$branch" ]; then
    if [ -f "/usr/local/nest/config/branch" ]; then
        branch=$(cat /usr/local/nest/config/branch)
    else
        branch="master"
    fi
fi
setStatusMessage "Selected branch: $branch"

if [ -d "/usr/local/nest/config" ]; then
    echo $branch > /usr/local/nest/config/branch

    setStatusMessage "Update your config from git"
    cd /usr/local/nest/config

    git fetch -q
    git checkout $branch --force
    git reset --hard origin/$branch
else
    setStatusMessage "Getting the nest config"
    git clone -q -b $branch https://github.com/sudarkoff/nest.git /usr/local/nest/config
fi

cd /usr/local/nest

setStatusMessage "Create ansible.cfg"
{ echo '[defaults]'; echo 'roles_path=/usr/local/nest/roles:/usr/local/nest/config/roles'; } > ansible.cfg

if [ -f "config/requirements.yml" ]; then
    setStatusMessage "Getting external roles"
    ansible-galaxy install -f -r config/requirements.yml -p roles
fi

setStatusMessage "Running the playbook"
ansible-playbook -i "localhost," $computername $extra_ansible_opts config/site.yaml
