---
- name: install the launchd script
  template:
    src: "{{ nest_plist_name }}.tpl"
    dest: "{{ launchd_path }}/{{ nest_plist_name }}.plist"

- name: load the launchd script
  command: launchctl load {{ launchd_path }}/{{ item }}.plist
  with_items:
    - "{{ nest_plist_name }}"
