---
- name: install zsh
  homebrew: name={{item}} state=latest
  with_items:
    - zsh

- name: install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto recursive=yes force=yes

- name: install .z files
  file: src=~/.zprezto/runcoms/{{item}} dest=~/.{{item}} state=link
  with_items:
    - zshenv
    - zprofile
    - zshrc
    - zlogin
    - zlogout

- name: install .zpreztorc
  copy: src=~/.zprezto/runcoms/zpreztorc dest=~/.zpreztorc force=yes

- set_fact:
    custom_prezto_modules:
      - dirmark
      - homebin
    standard_prezto_modules:
      - git
      - osx
      - syntax-highlighting
      - history-substring-search
      - ssh

- set_fact:
    prezto_modules:
      "{{ custom_prezto_modules + standard_prezto_modules }}"

- name: install custom prezto modules
  copy: src=modules/{{item}} dest=~/.zprezto/modules force=yes
  with_items: "{{custom_prezto_modules}}"

- name: add prezto modules to .zpreztorc
  lineinfile: "dest=~/.zpreztorc insertbefore=\"^  'prompt'\" line=\"  '{{item}}' \\ \""
  with_items: "{{prezto_modules}}"

- name: remove trailing spaces
  replace: dest=~/.zpreztorc regexp="\s*$"

- name: install custom theme
  copy: src=themes/prompt_sudarkoff_setup dest=~/.zprezto/modules/prompt/functions/

- name: configure custom prompt
  lineinfile: >
    dest=~/.zpreztorc
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    backrefs=yes
    create=true
  with_items:
    - { regexp: "zstyle ':prezto:module:prompt' theme 'sorin'", line: "zstyle ':prezto:module:prompt' theme 'sudarkoff'" }

- name: change shell to zsh
  command: chsh -s /bin/zsh
  become: yes
