---
- name: create ~/bin
  copy:
    src: bin/
    dest: "/Users/{{ username }}/bin"
    owner: "{{ username }}"

- name: make certain ~/bin scripts executable
  file:
    path: "/Users/{{ username }}/{{ item }}"
    mode: "u+x"
  with_items:
    - bin/jlog
    - bin/pmake

- name: make git scripts executable
  file:
    path: "/Users/{{ username }}/bin/git/{{ item | basename }}"
    mode: "u+x"
  with_fileglob:
    - bin/git/git-*
