---
- name: install brew applications
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{brew_apps}}"

- name: install brew cask applications
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items: "{{brew_cask_apps}}"
