---
- name: register the current terminal profile
  shell: defaults read "com.apple.Terminal" "Default Window Settings"
  register: terminal_profile_result
  changed_when: False

- name: store the terminal profile in /tmp
  copy:
    src: "homebrew-andale-mono24.256.terminal"
    dest: "/tmp/homebrew-andale-mono24.256.terminal"
  when: terminal_profile_result.stdout != "homebrew-andale-mono24.256"

- name: install the terminal profile
  shell: open /tmp/homebrew-andale-mono24.256.terminal
  when: terminal_profile_result.stdout != "homebrew-andale-mono24.256"

- name: set the Default Window Settings
  osx_defaults:
    domain: com.apple.Terminal
    key: Default Window Settings
    type: string
    value: "homebrew-andale-mono24.256"
    state: present

- name: set the Startup Window Settings
  osx_defaults:
    domain: com.apple.Terminal
    key: Startup Window Settings
    type: string
    value: "homebrew-andale-mono24.256"
    state: present
