---
dependencies:
  - role: sudoers
  - role: osx_defaults
  - role: computername
    when: computername is defined
  - role: launchd
  - role: ssh_config
  - role: fonts
  - role: terminal
  - role: slate
  - role: git
  - role: vim
  - role: zsh
  - role: bin
