---
- name: install macvim
  homebrew_cask: name={{item}} state=present
  with_items:
    - macvim

- name: copy .vim
  copy: src=vim dest=~/.vim

- name: copy .vimrc
  copy: src=vimrc dest=~/.vimrc

- name: install vundle
  shell: git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

- name: install vundles
  shell: vim --noplugin -u ~/.vim/vundles.vim -N "+set hidden" "+syntax on" +BundleClean +BundleInstall +qall
