---
- name: create ssh directory
  become: yes
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: wheel
    mode: 0777
  with_items:
    - /etc/ssh

- name: ssh config
  become: yes
  copy:
    src: ssh_config
    dest: /etc/ssh_config

- name: ssh config in another location
  become: yes
  copy:
    src: ssh_config
    dest: /etc/ssh/ssh_config

